
import * as ts from "typescript";

export function substr(fullcontent: string, node: ts.Node) {
    return fullcontent.substring(node.pos, node.end);
  }
export function warning(){
    return `// DO NOT MODIFY!.
// generated by api_generator.js, it will be overwrite eventually!
`}

export function onceWarning(){
    return `// MODIFIALBE! 
// generated by api_generator.js,
// only generated when file is not existed!
`}
