const { exec } = require("child_process");
import * as ts from "typescript";

export function substr(fullcontent: string, node: ts.Node) {
    return fullcontent.substring(node.pos, node.end);
  }
export function warning(){
    return `// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!
`}

export function onceWarning(){
    return `// MODIFIALBE! 
// generated by x-cli,
// only generated when file is not existed!
`}

export function run(cmd) {
    exec(cmd, (error, stdout, stderr) => {
      if (error) {
        console.log(`error: ${error.message}`);
        return;
      }
      if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
      }
      console.log(`stdout: ${stdout}`);
    });
  }

