const { exec } = require("child_process");
import * as ts from "typescript";

export function substr(fullcontent: string, node: ts.Node) {
    return fullcontent.substring(node.pos, node.end);
  }
export function warning(){
    return `// DO NOT MODIFY!.
// generated by x-cli, it will be overwrite eventually!
`}

export function onceWarning(){
    return `// MODIFIALBE! 
// generated by x-cli,
// only generated when file is not existed!
`}

export function run(cmd, cb?, ecb?) {
    exec(cmd, (error, stdout, stderr) => {
      if(error || stderr)
        console.log(stdout, error,stderr)

      if (error) {
        if (ecb) {
          ecb(error, stderr);
        } else {
          console.log(`${stdout} ${error} ${stderr}`);
        }
        return;
      }
      if(cb)
        cb(stdout);
      else{
        console.log(stdout)
      }
    });
  }

